MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/nightVisionScript.cs
MoreShipUpgrades/UpgradeComponents/pagerScript.cs

pager can only be used once per 30 seconds (configurable, meant to not negate walkies) as well as added night vision tiers. each tier increases the regen speed by 20%, and decreases the drain speed by 10% (both percentages configurable)
let me know if we should just make the pager work in tiers for a lower cooldown as well, im not fully sure what the right balance should be for it since we have such short messages from the pager as a possibility

Pager changes and nightvision tiers

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/StartOfRoundPatcher.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/playerHealthScript.cs

Made a new upgrade called "Stimpack" which basically increases the player's health.
Sounds easy enough right? Just increase the max health of the player and be going with it.
WELL, apparently it's just one variable for health and it's the current one so I had to be creative.
Whenever the player buys the upgrade or increments the level, check if it's the local player that bought it to update the health.
Whenever a new round starts, each player's health gets updated if they have any entries in the dictionary associated to this upgrade (which stores the amount of health they will have). If so, put the respective value into their health and update the HUD.
This obviously won't work if any other mods that regen health as they all, and rightfully so, set the health value to the default which is …

Implementation of Player Health Upgrade (Stimpack)

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Patches/PlayerControllerBPatcher.cs
MoreShipUpgrades/UpgradeComponents/MedkitScript.cs
MoreShipUpgrades/UpgradeComponents/defibScript.cs
MoreShipUpgrades/UpgradeComponents/playerHealthScript.cs

Fixed medkit not releasing player from Critical Injury state when used and heals pasts the critical threshold.
Added a fix for DamagePlayer resetting any additional health from Stimpack back to 100 due to Mathf.Clamp being restricted between 0 to 100

Fixing Medpack & Stimpack

---

MoreShipUpgrades/Patches/StartOfRoundPatcher.cs

Requested by [this comment](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/79#issuecomment-1868562789), instead of updating the health values whenever the ship's doors open upon entering the moon, we just do the same logic in the DamagePlayer transpiler which is we use the value from Stimpack Upgrade instead of vanilla to update the player's health.

Made transpiler for ReviveDeadPlayers to update health values according to Stimpack upgrade

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Patches/PlayerControllerBPatcher.cs
MoreShipUpgrades/Patches/RedLocustBeesPatch.cs
MoreShipUpgrades/UpgradeComponents/beekeeperScript.cs

The transpiler now changes the damageNumber according to the state of beekeeper level and unlock before it's received by DamagePlayer in RedLocustBee.
With this, we do not need the RPCs related to storing the beekeeper level of each player

Changed PlayerControllerB's pre patches related to Beekeeper to a transpiler in RedLocustBees

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/BaseUpgrade.cs
MoreShipUpgrades/Misc/LGULogger.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/RedLocustBeesPatch.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/beekeeperScript.cs
MoreShipUpgrades/UpgradeComponents/biggerLungScript.cs
MoreShipUpgrades/UpgradeComponents/exoskeletonScript.cs
MoreShipUpgrades/UpgradeComponents/hunterScript.cs
MoreShipUpgrades/UpgradeComponents/lightFootedScript.cs
MoreShipUpgrades/UpgradeComponents/lightningRodScript.cs
MoreShipUpgrades/UpgradeComponents/lockSmithScript.cs
MoreShipUpgrades/UpgradeComponents/nightVisionScript.cs
MoreShipUpgrades/UpgradeComponents/pagerScript.cs
MoreShipUpgrades/UpgradeComponents/playerHealthScript.cs
MoreShipUpgrades/UpgradeComponents/proteinPowderScript.cs
MoreShipUpgrades/UpgradeComponents/runningShoeScript.cs
MoreShipUpgrades/UpgradeComponents/strongLegsScript.cs
MoreShipUpgrades/UpgradeComponents/strongerScannerScript.cs
MoreShipUpgrades/UpgradeComponents/terminalFlashScript.cs
MoreShipUpgrades/UpgradeComponents/trapDestroyerScript.cs
MoreShipUpgrades/UpgradeComponents/walkieScript.cs

Made "BaseUpgrade" have the strings related to Individual status and prices' configurations, since all upgrades had the same string. 
BaseUpgrade's methods now do the send message to chat where it uses a variable that stores the derived's upgrade name and the register. 
Moved all prices' default of each upgrade to their respective scripts. Passed LogInfo to LogDebug to not overload the console with useless logs such as loading assets.
Remove string.Format from logs since it's computionally costly than doing $"string" way.

Refactoring of BaseUpgrade and derived classes

---

MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/PlayerControllerBPatcher.cs
MoreShipUpgrades/UpgradeComponents/biggerLungScript.cs

Added configuration values for both Stamina regeneration rate increase and stamina cost decrease on jumps related to Bigger Lungs. Through transpilers, we pick up the intended value that represents the each of these and change it according to the upgrade.

Implementation of Bigger Lungs' stamina regen increase and reduction of stamina cost on jumps

---

MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/UpgradeComponents/terminalFlashScript.cs

Added configuration for:
- The first level in which the discombobulator starts dealing damage to enemies when activated
- The initial amount of damage it deals when reaching the first level of discombobulator which allows damaging enemies
- The incremental amount of damage when the discombobulator is upgraded past the initial level of damage.

Implemented discombobulator dealing damage past a certain level

---

MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/PlayerControllerBPatcher.cs
MoreShipUpgrades/UpgradeComponents/strongLegsScript.cs

The multiplier that serves as the damage mitigation of fall damage is configurable.
It will still play the damagePlayer animation but it won't actually hurt the player in terms of health.

Implementation of Strong Legs' last level applying damage reduction when falling from high heights

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/DeleteButtonPatcher.cs
MoreShipUpgrades/Patches/GameNetworkManagerPatcher.cs
MoreShipUpgrades/Patches/InteractTriggerPatcher.cs
MoreShipUpgrades/Patches/RedLocustBeesPatch.cs
MoreShipUpgrades/Patches/SandSpiderAIPatcher.cs
MoreShipUpgrades/Patches/ShovelPatcher.cs
MoreShipUpgrades/Patches/SpringManAIPatcher.cs
MoreShipUpgrades/Patches/StartOfRoundPatcher.cs
MoreShipUpgrades/Patches/StormyWeatherPatcher.cs
MoreShipUpgrades/UpgradeComponents/biggerLungScript.cs
MoreShipUpgrades/UpgradeComponents/lightningRodScript.cs
MoreShipUpgrades/UpgradeComponents/runningShoeScript.cs
MoreShipUpgrades/UpgradeComponents/strongLegsScript.cs
MoreShipUpgrades/UpgradeComponents/strongerScannerScript.cs
MoreShipUpgrades/UpgradeComponents/terminalFlashScript.cs

- All the initial values of each upgrade are now what's added to the player's respective attributes. This allows compatibility between mods that want to change the player's attributes without any upgrades (only on start, mods that change these attributes with a set rather than adding or removing will nullify any effects of the upgrades til server restart).
- Strong Legs was not applying the jump force increment whenever it was upgrade past the first level. It only loaded back with proper value when the lobby was restarted.
- Changed any LogInfo to LogDebug to not clutter the user's console with lightning catching logs.
- Added LogDebugs in relevant areas to know when something is working properly or not.
- Added LogErrors in transpilers when it's not found sufficient instruction codes to …

Changed logic of Running Shoes, Bigger Lungs and Strong Legs configuration values

---

MoreShipUpgrades/UpgradeComponents/biggerLungScript.cs
MoreShipUpgrades/UpgradeComponents/runningShoeScript.cs
MoreShipUpgrades/UpgradeComponents/strongLegsScript.cs

For correcting the code merged [related to Running Shoes, Bigger Lungs and Strong Legs](https://github.com/Malcolm-Q/LC-LateGameUpgrades/pull/136) for "Load LGU" calling load method of BaseUpgrade which always has "+=" instead of the old "=" at the beginning to reset the value. This way, we will only increment by the necessary amount when syncing upgrades between players.

Corrections needed due to Load LGU causing the attributes to be always increasing.

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Misc/CustomTerminalNode.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/RoundManagerPatcher.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/ExtendDeadlineScript.cs

- Displayed in the ``lgu`` and ``lategame store`` command with the name of ``Extend Deadline``
- Info of "Extend Deadline" tells the user that they can increase the days before deadline by x amount (so long as they have the credits for it)
- Allows the lobby to purchase x amount of days to go scavenging for more scrap.
- Configuration
- Enabled (default: true)
- Price of each day ( default: 1500)
Since it was given as a [suggestion](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/127)

Implementation of "Extend Deadline <days>" command, implemented "IComparable" interface on CustomTerminalNode

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/EnemyAIPatcher.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/hunterScript.cs

Namely how many tiers it can have (through the amount of prices inserted in the configuration); At which tier each sample can spawn at (through a list of lists where each tier is separated by dashes and each sample is separated by commas) And the minimum/maximum scrap value each sample can have.
Implemented for given [suggestion](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/83)

Added Configuration to the Hunter Upgrade

---

.gitignore
MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/biggerLungScript.cs
MoreShipUpgrades/UpgradeComponents/runningShoeScript.cs
MoreShipUpgrades/UpgradeComponents/strongLegsScript.cs

This should allow compatibility with mods that also alter the same parameters. 
Health upgrade still needs to be looked at.

Changing reset functions' logic to just remove the increments done by each upgrade on the player instead of setting to default vanilla value

---

MoreShipUpgrades/Patches/EnemyAIPatcher.cs
MoreShipUpgrades/UpgradeComponents/hunterScript.cs

Since we allow lists with spaces in between commas and names, we forgot to trim the values so that "Contains" can work as expected.

Fixing issue #146

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/MoreShipUpgrades.csproj
MoreShipUpgrades/Patches/PlayerControllerBPatcher.cs
MoreShipUpgrades/UpgradeComponents/BeatScript.cs

- Instead of changing whenever a player dies, just look at Update to see if the player is dead or not to remove the effects (if they had any). Also no point checking for boomboxes if the player's dead.
- Though a suggestion would be to make a circular collider for this as we only need to know when they get in and out of the area of the boombox. I will look more into this later.
- Sick beats wasn't being saved, fixed that issue too.

Changed Sick Beats way of checking to remove effect

---

MoreShipUpgrades/Patches/HUDManagerPatcher.cs
MoreShipUpgrades/Patches/HoarderBugAIPatcher.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/BombDefusalScript.cs
MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/ScrapWheelbarrow.cs
MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/StoreWheelbarrow.cs
MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/WheelbarrowScript.cs

- Stopped the ticking sound after the bomb has been defused
- Hoarding bugs will only get angry when the contract type saved with "exterminator" (if the contract type is not reset after completing it, it will start making them angry, make sure that it resets)
- Fixed the issue with wheelbarrow and shopping cart not being saved (making a deep copy of their itemProperties would make them be unable to be saved thus disappearing after relog)
- This also means that I had to change its total weight logic as it was using itemProperties as a mean to store all items' weight.
- Items while being carried in a wheelbarrow will not have their scan nodes displayed in the player's HUD.

Multiples fixes and changes to wheelbarrow's and contract's behaviours

---

MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/ExtractPlayerScript.cs
MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/WheelbarrowScript.cs

- Changed the total weight calculation to be synced with everyone and not applying more than once (aka the RPCs are probably deemed useless but I can't bother cleaning that up right now)
- Changed the variable attribution of itemProperties.weight from after being inserted in allItemsList to before to not cause any instance of this item to not save.

Fixes in Wheelbarrow and Scavenger

---

MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/WheelbarrowScript.cs

- Fixed weight having an additional 1 lb compared to configuration.
- Fixed some of scrap wheelbarrow's configuration options to not appear due to duplicate keys
- Possibly fixed enabled scrap wheelbarrow configuration not being used
- Fixed scrap items not appearing as "looted" when dropped in the ship inside a wheelbarrow

Fixes to Wheelbarrow

---

MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Patches/TerminalPatcher.cs

- When a contract has been accepted but the crew does not want to do it, they can type "contract cancel" to get rid of it.
- Will make a prompt to confirm to execute this confirm and if the user types anything other than "confirm", the cancel contract command is cancelled.
- After confirming the command, the selected contract will be reset to all clients through RPCs and they can decide to purchase another contract if they wish to.
Due to suggestion in a [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/203)

Implemented "Contract Cancel" command

---

MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/HUDManagerPatcher.cs
MoreShipUpgrades/Patches/RoundManagerPatcher.cs
MoreShipUpgrades/Patches/RoundManagerTranspilerPatcher.cs
MoreShipUpgrades/Patches/TerminalPatcher.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/Commands/ScrapInsurance.cs

- Allows you to keep scrap after a team wipe when bought
- Default price is 400 credits (configurable)
- Implementation wise, two transpilers which stop the hud from displaying "All scrap lost" and the logic which deletes all scrap items in the ship if all players are dead and a postifx after the attempted deletion to turn off scrap insurance.
- I really wanted to use ScrapInsurance as Singleton but for some reason it doesn't load so Start never starts. I have no idea what's happerning. :c
As suggested in a [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/151)

Implementation of Scrap Insurance

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Managers/UpgradeBus.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/TierUpgrades/DoorsHydraulicsBattery.cs
UnityFiles/ShipUpgrades/DoorsHydraulicsBattery.prefab
UnityFiles/ShipUpgrades/DoorsHydraulicsBattery.prefab.meta

- Increases the amount of time in which the doors remain closed
- Default initial price is 300
- Default prices are 200, 300 and 400
- Default initial battery boost is 5 (vanilla's initial value seems to be 30)
- Default incremental battery boost is 5
- The logic behind the upgrade is basically increasing the value of HangarShipDoor.doorPowerDuration to increase the amount of time it keeps closed (HangarShipDoor.doorPower is the ship's current % battery)
- Implementation wise, the resets of the ship's attributes must be done through RPCs so that everyone's have the exact same behaviour with the ship.
This in suggestion to a given [issue](https://github.com/Malcolm-Q/LC-LateGameUpgrades/issues/170)

Implementation of Doors Hydraulic Battery Boost upgrade (named "Shutter Batteries")

---

MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Patches/TerminalPatcher.cs

- Implemented "contract [moon]" where the player can specify which moon they want to have a contract on. This will use a different price (configurable) and searches if that moon in fact exists to select. After finding it, it will ask the player to confirm the interaction and if so, it will use that moon as for the generated contract.
- Implemented "contract" being able to select any kind of moon present/loaded into the game instead of a set list we had before (this would allow limitation on custom moons) and added a configuration option for where random contract will only select free moons or it will pick any kind of moon. Also added a failsafe incase all of the moons somehow have a cost while having the free moons only configuration on in which it selects the last level it picked.

Two features implemented for Contracts system

---

MoreShipUpgrades/UpgradeComponents/Items/NightVisionGoggles.cs

Problem here was we were doing "If this upgrade is not shared, share to others" instead of "If this upgrade is shared, share to others"

Fixing night vision being enabled for everyone when individual is on and shared all upgrades is off

---

MoreShipUpgrades/UpgradeComponents/Items/Wheelbarrow/WheelbarrowScript.cs

I'm not sure if the RPC is applying multiple times to the same player the calculations leading to constantly increasing your weight to infinity but this seems to be working at LAN level, we'll have to see at online level.

Possible fix for people having left over weight when dropping the wheelbarrow

---

MoreShipUpgrades/UpgradeComponents/Items/Medkit.cs

This is to prevent cases of mods patching DamagePlayer which introduce damage reduction of rendering the medkit useless.

Changing medkit's healing method to just add to the attribute instead of using DamagePlayer with negative value

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Misc/PluginConfig.cs

Created a new class which stores all the configuration property values and sends it to the clients. The method of getting the methods is done through Reflection for easier code maintenance and doesn't force the class to know what properties there are.

Fixed configuration synchronization not working due to ConfigEntry not being serializable

---

MoreShipUpgrades/Misc/CommandParser.cs
MoreShipUpgrades/Patches/Items/ShovelPatcher.cs
MoreShipUpgrades/UpgradeComponents/OneTimeUpgrades/SickBeats.cs
MoreShipUpgrades/UpgradeComponents/TierUpgrades/ProteinPowder.cs

Split the ``GetShovelHitForce()`` implementation between ProteinPowder and SickBeats for easier logic handling and to distribute responsibilities to respective classes.

Fixing Sick Beats being disabled preventing enemy damage

---

MoreShipUpgrades/Patches/Enemies/EnemyAIPatcher.cs
MoreShipUpgrades/UpgradeComponents/Contracts/DefusalContract.cs
MoreShipUpgrades/UpgradeComponents/Contracts/ExtractionContract.cs
MoreShipUpgrades/UpgradeComponents/Items/Contracts/BombDefusal/BombDefusalScript.cs
MoreShipUpgrades/UpgradeComponents/Items/Contracts/Extraction/ExtractPlayerScript.cs

- Possibly fixed samples spawning more than once, leading to the other being not interactable.
- Fixed bomb and scavenger item disappearing after a save reboot due its initial state initialization ignoring if it was stored in the ship.

Fixes on sample spawning and contract during reboot

---

MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Patches/PlayerController/PlayerControllerBPatcher.cs
MoreShipUpgrades/UpgradeComponents/Items/Peeper.cs
MoreShipUpgrades/UpgradeComponents/Items/PortableTeleporter/BasePortableTeleporter.cs
MoreShipUpgrades/UpgradeComponents/TierUpgrades/AttributeUpgrades/Stimpack.cs

- Fixed Stimpack not working when reviving players/regenerating them back to full health.
- Stopped Beats check on PlayerControllerB if it's disabled.
- Fixed Portable Teleporters being restricted to mouse left click regardless of binding change for item interaction.
- Fixed Peeper throwing error when the list of peepers is changed during iteration.

Fixes for items, Sick Beats and Stimpack

---

MoreShipUpgrades/Input/Keybinds.cs
MoreShipUpgrades/Managers/ConfigSynchronizationManager.cs

Just like the nvg color have an exception I added an exception for nvg and wheelbarrow keybinds when synching config.

Prevent keybind sync for wheelbarrow and nvg

---

MoreShipUpgrades/Managers/ConfigSynchronizationManager.cs
MoreShipUpgrades/Managers/LGUStore.cs
MoreShipUpgrades/Patches/Items/BoomBoxPatcher.cs

- Changed the patch from applying on ``BoomboxItem.Start`` to apply on ``BoomboxItem.StartMusic`` where it adds to the list used by Sick Beats if it's not already in.
- Added more time between config sync and loading gameobjects for no mix of synchronized and unsynchronized values.

Fixed issue between DiscJockey and this mod

---

MoreShipUpgrades/API/HunterSamples.cs
MoreShipUpgrades/Misc/AssetBundleHandler.cs
MoreShipUpgrades/Misc/UI/Application/UpgradeStoreApplication.cs
MoreShipUpgrades/MoreShipUpgrades.csproj
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/Items/MonsterSample.cs

potential fix for particles not stopping/cleaning (not sure if it's really a problem or not)
fix forestgiant samplePaths
change InteractiveTerminalAPI to publicize and use the thunderstore folder structure 
add IsHunterEnabled to hunter api so other mods can test without making csync a dependency (maybe useful?)

Fix for hunter upgrade and other small fixes

---

MoreShipUpgrades/Misc/PluginConfig.cs
MoreShipUpgrades/Misc/Util/LGUConstants.cs
MoreShipUpgrades/Patches/PlayerController/PlayerControllerBPatcher.cs

Currently, nothing prevents you from switching off of a wheelbarrow / shopping cart when deeper pockets is enabled. This creates
a glitch and the player becomes unable to drop any items or interact with anything.
This patch basically prevents the wheelbarrow from ever being treated as one-handed by deeper pockets.
Fixes #458.

Prevent deeper pockets from letting you switch off a wheelbarrow

---

MoreShipUpgrades/Compat/BrutalCompanyMinusExtraCompat.cs
MoreShipUpgrades/Managers/PatchManager.cs
MoreShipUpgrades/Plugin.cs
MoreShipUpgrades/UpgradeComponents/TierUpgrades/Player/Beekeeper.cs

Fixes:
- Brutal Company Minus Extra mod uses it's own code to spawn scrap inside and outside, which obviously doesnt use Midas Touch scrap value multipliers. Also brutal company can transmute scrap or hazards into different scraps, which wont use Midas Touch multiplier aswell. First commit fixes that.
- Beekeeper upgrade applied hive scrap value increase only until host restarts the lobby. Second commit fixes that.
Tested everything both in multiplayer and singleplayer, everything worked well on our config. I hope no further issues arise from these changes.

BrutalCompanyMinusExtra compatibility and Beekeeper fix

---

MoreShipUpgrades/Compat/BrutalCompanyMinusExtraCompat.cs
MoreShipUpgrades/Managers/PatchManager.cs
MoreShipUpgrades/Patches/Items/BeltBagItemPatcher.cs
MoreShipUpgrades/Plugin.cs

Hello!
This PR fixes:
- Compatibility between LGU's Midas Touch and [Brutal Company Minus Extra Reborn](https://thunderstore.io/c/lethal-company/p/SoftDiamond/BrutalCompanyMinusExtraReborn/). That was already done to Brutal Company Minus Extra, so fixes are the same, but now they work for Reborn version. This time **no need to insert new dependencies** in .csproj file.
- Mechanical Arms not increasing Belt Bag interaction distance (pressing Q to store items), which was confusing to me.
Tested both fixes in singleplayer, for me everything works fine.

BCME Reborn Compat + Mechanical Arms Belt Bag fix
